In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("killa92/crop-disease-image-classification-dataset")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/killa92/crop-disease-image-classification-dataset/1.archive...

100%|██████████| 2.00G/2.00G [00:29<00:00, 73.3MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/killa92/crop-disease-image-classification-dataset/versions/1

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import os
print(os.listdir(path))

['crop_disease_dataset']

In [16]:
csv_path = os.path.join(path, "crop_disease_dataset")
print(os.listdir(csv_path))

['images', 'class_names.json', 'meta_deta.csv']

In [13]:
df = pd.read_csv(os.path.join(csv_path, "meta_deta.csv"), on_bad_lines="skip")
df.head()

         image_id  label
0  1000015157.jpg      0
1  1000201771.jpg      3
2   100042118.jpg      1
3  1000723321.jpg      1
4  1000812911.jpg      3

In [15]:
df.tail()

            image_id  label
21392  999068805.jpg      3
21393  999329392.jpg      3
21394  999474432.jpg      1
21395  999616605.jpg      4
21396  999998473.jpg      4

In [17]:
df['label'].value_counts()

label
3    13158
4     2577
2     2386
1     2189
0     1087
Name: count, dtype: int64